---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-ns-labels
  annotations:
    policies.kyverno.io/description: >-
      check for required namespace labels
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: check-ns
      match:
        resources:
          kinds:
            - Namespace
      validate:
        message: >-
          The namespace must have a label 'role' with a value 'devtest' or 'prod'
        pattern:
          metadata:
            labels:
              role: "devtest | prod"
