apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-nodeselector
  annotations:
    policies.kyverno.io/description: >- 
      inject a nodeSelector based on the namespace role
spec:
  rules:
  - name: spot
    match:
      resources:
        kinds:
        - Pod
        namespaceSelector:
          matchLabels:
            role: devtest
    mutate:
      patchStrategicMerge:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
            karpenter.sh/capacity-type: spot
  - name: on-demand
    match:
      resources:
        kinds:
        - Pod
        namespaceSelector:
          matchLabels:
            role: prod
    mutate:
      patchStrategicMerge:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
            karpenter.sh/capacity-type: on-demand
