apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-labels
  annotations:
    policies.kyverno.io/title: Add User Labels 
    policies.kyverno.io/category: PCI
    policies.kyverno.io/description: >-
      Add the username as a label to namespaces and workloads.    
spec:
  background: false
  rules:
  - name: add-user-labels
    match:
      resources:
        kinds:
        - Namespace
        - Pod
    mutate:
      overlay:
        metadata:
          labels:
            kyverno.io/createdBy: "{{request.userInfo.username}}"

