apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-annotations
  annotations:
    policies.kyverno.io/title: Add User Data 
    policies.kyverno.io/category: PCI
    policies.kyverno.io/description: >-
      Add the username as an annotation for namespaces and workloads.    
spec:
  background: false
  rules:
  - name: add-user-data
    match:
      resources:
        kinds:
        - Namespace
        - Pod
    mutate:
      overlay:
        metadata:
          annotations:
            kyverno.io/createdBy: "{{request.userInfo.username}}"

