---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx
spec:
  replicas: 1 
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: "nginx"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: nginx
    spec:
      containers:
      - name: "nginx"
        image: "public.ecr.aws/nginx/nginx:alpine"
        ports:
        - containerPort: 8080
          protocol: "TCP"
